### ISSUE TITLE
Rename this extension to yii2-yii-bridge or clarify the purpose

### ISSUE THREAD

**Issue by motin** [slavcodev/yii2-yii-bridge#6]
It seems that this extension allows one to use old models in your Yii2 application, but not the other way around. Is this so?

Thus, this is a Yii 2 extension? If so, it should be prefixed by "yii2-".

**Comment by schmunk42** [comment]
Agree with @motin all Yii 2.0 extensions should be prefixed with `yii2`.

**Comment by slavcodev** [comment]
@schmunk42, As I mention above, IMO, It isn't an extension for Yii2.

**Comment by motin** [comment]
@slavcodev As I understand it, it is meant to be used in Yii 2 applications, and not in Yii 1 applications (Example in readme says "Save Yii1 AR in Yii2 controller"). Any piece of reusable component that is meant to be used in Yii 2 applications is basically a Yii 2 extension. 

Also, look at it from an external user's perspective. Bobby has a Yii 2 application and wants to use Yii 1 models. Alice has a Yii 1 application and want to use Yii 2 widgets. The following extensions are available currently:

 yii-bridge
 yii-yii2-bridge

It is not evident which extension is for which purpose. If however they would be named like so:

 yii2-yii-bridge
 yii-yii2-bridge

... one would immediately understand which component is meant to be included in a Yii 2 application and which one to be included in a Yii 1 application. 

Also, read the guidelines from http://www.yiiframework.com/doc-2.0/guide-structure-extensions.html#package-name: 

> We recommend you prefix yii2- to the project name for packages representing Yii 2 extensions, for example, myname/yii2-mywidget. This will allow users to more easily tell whether a package is a Yii 2 extension.

**Comment by slavcodev** [comment]
OK, guys! Will do in next week.

**Comment by slavcodev** [comment]
Done.

**Comment by motin** [comment]
Thanks for bringing clarity :)
